### ISSUE TITLE
Set VAULT_TOKEN and NOMAD_TOKEN at startup of box

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#151]
VAULT_TOKEN and NOMAD_TOKEN are both empty when the box is started. They should by `master` and `<bootstrap-token>` respectively. `bootstrap-token` is not known before the box is started, but is set after `nomad acl bootstrap` is run from the `nomad_acl_bootstrap.yml` playbook. A potential solution is setting the variable in the `nomad_acl_boostrap`-playbook, or right after, in the `bootstrap.yml`-playbook.

**Comment by fredrikhgrelland** [comment]
I suggest this to be added to bashrc or maybe we could transition to zsh? :+1: 

Variables we need are:
- CONSUL_TOKEN
- CONSUL_ADDR
- CONSUL_HTTP_ADDR
- VAULT_TOKEN
- VAULT_ADDR
- VAULT_HTTP_ADDR
- NOMAD_TOKEN
- NOMAD_ADDR

**Comment by zhenik** [comment]
> I suggest this to be added to bashrc or maybe we could transition to zsh? 👍
> 
> Variables we need are:
> 
> * CONSUL_TOKEN
> * CONSUL_ADDR
> * CONSUL_HTTP_ADDR
> * VAULT_TOKEN
> * VAULT_ADDR
> * VAULT_HTTP_ADDR
> * NOMAD_TOKEN
> * NOMAD_ADDR

WDYT about this approach https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/ansible/install.yml#L130-L136 ?

**Comment by fredrikhgrelland** [comment]
> > I suggest this to be added to bashrc or maybe we could transition to zsh? +1
> > Variables we need are:
> > 
> > * CONSUL_TOKEN
> > * CONSUL_ADDR
> > * CONSUL_HTTP_ADDR
> > * VAULT_TOKEN
> > * VAULT_ADDR
> > * VAULT_HTTP_ADDR
> > * NOMAD_TOKEN
> > * NOMAD_ADDR
> 
> WDYT about this approach https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/ansible/install.yml#L130-L136 ?
> 
> ps. It does NOT work if you need to run commands via vagrant remotely -> `vagrant ssh -i "COMMAND 1; COMMAND 2"`

It could be done in one command e.g : 
```
lineinfile:
          path: /etc/httpd/conf/httpd.conf
          # The String to Search
          regexp: "LogLevel warn" 
          # The String to Replace
          line: "LogLevel debug"
          state: present
          backup: yes
```

use regexp to test and add line if not exists.

I would like the bashrc to be correct after startup so any use of the shell when logging in makes sense. In addition, we could get rid of all env setting in all ansible playbooks....
