### ISSUE TITLE
add the enterprise variables in github action to override the default values for them and that would verify the toggle.

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#197]
True.. that! However, we need to add the new variables in github action to override the default values for them and that would verify the toggle.

_Originally posted by @Neha-Sinha2305 in https://github.com/fredrikhgrelland/vagrant-hashistack/pull/196#issuecomment-674041839_

**Comment by Neha-Sinha2305** [comment]
@zhenik, @fredrikhgrelland , @pdmthorsrud 

Does this strategy looks OK to you :
```
    strategy:
      matrix:
        consul_acl: ["consul_acl_enabled", "consul_acl_disabled"]
        consul_acl_default_policy: ["consul_acl_deny"]
        nomad_acl: ["nomad_acl_enabled", "nomad_acl_disabled"]
        hashicorp_binary: ["hashicorp_oss", "hashicorp_enterprise"]
```
**Note:** hashicorp_oss : runs the opensource versions of consul,vault,nomad and hashicorp_enterprise runs the enterprise version.

This yields 8 combinations:

1.  test (consul_acl_enabled, consul_acl_deny, nomad_acl_disabled, hashicorp_oss)
2.  test (consul_acl_enabled, consul_acl_deny, nomad_acl_disabled, hashicorp_enterprise)

3. test (consul_acl_enabled, consul_acl_deny, nomad_acl_enabled, hashicorp_oss)
4.  test (consul_acl_enabled, consul_acl_deny, nomad_acl_enabled, hashicorp_enterprise)

5. test (consul_acl_disabled, consul_acl_deny, nomad_acl_disabled, hashicorp_oss)
6.  test (consul_acl_enabled, consul_acl_deny, nomad_acl_disabled, hashicorp_enterprise)

7. test (consul_acl_disabled, consul_acl_deny, nomad_acl_enabled, hashicorp_oss)
8.  test (consul_acl_enabled, consul_acl_deny, nomad_acl_enabled, hashicorp_enterprise)

Should we reduce? Do all of these provide useful info?

**Comment by pdmthorsrud** [comment]
> @zhenik, @fredrikhgrelland , @pdmthorsrud
> 
> Does this strategy looks OK to you :
> 
> ```
>     strategy:
>       matrix:
>         consul_acl: ["consul_acl_enabled", "consul_acl_disabled"]
>         consul_acl_default_policy: ["consul_acl_deny"]
>         nomad_acl: ["nomad_acl_enabled", "nomad_acl_disabled"]
>         hashicorp_binary: ["hashicorp_oss", "hashicorp_enterprise"]
> ```
> 
> **Note:** hashicorp_oss : runs the opensource versions of consul,vault,nomad and hashicorp_enterprise runs the enterprise version.
> 
> This yields 8 combinations:
> 
> 1. test (consul_acl_enabled, consul_acl_deny, nomad_acl_disabled, hashicorp_oss)
> 2. test (consul_acl_enabled, consul_acl_deny, nomad_acl_disabled, hashicorp_enterprise)
> 3. test (consul_acl_enabled, consul_acl_deny, nomad_acl_enabled, hashicorp_oss)
> 4. test (consul_acl_enabled, consul_acl_deny, nomad_acl_enabled, hashicorp_enterprise)
> 5. test (consul_acl_disabled, consul_acl_deny, nomad_acl_disabled, hashicorp_oss)
> 6. test (consul_acl_enabled, consul_acl_deny, nomad_acl_disabled, hashicorp_enterprise)
> 7. test (consul_acl_disabled, consul_acl_deny, nomad_acl_enabled, hashicorp_oss)
> 8. test (consul_acl_enabled, consul_acl_deny, nomad_acl_enabled, hashicorp_enterprise)
> 
> Should we reduce? Do all of these provide useful info?

All of them seem like valid scenarios to me.

**Comment by Neha-Sinha2305** [comment]
Just a note : if we go with the below strategy then we will end up with **32** combinations and the tests will run forever before anything gets merged:
```
 strategy:
      matrix:
        consul_acl: ["consul_acl_enabled", "consul_acl_disabled"]
        consul_acl_default_policy: ["consul_acl_deny"]
        nomad_acl: ["nomad_acl_enabled", "nomad_acl_disabled"]
        consul_binary: ["consul_oss", "consul_enterprise"]
        nomad_binary: ["nomad_oss", "nomad_enterprise"]
        vault_binary: ["vault_oss", "vault_enterprise"]
```
