### ISSUE TITLE
Linter for `tf` files

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#301]
- [ ] Linter for `tf` files
- [ ] script running before commits -> `terraform fmt -recursive` (research)

**Comment by Neha-Sinha2305** [comment]
I guess we can use the following github action for tflint:
```
      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
```
https://github.com/reviewdog/action-tflint
