### ISSUE TITLE
Unnecessary commands in vault-integration.yml

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#417]
## Current behaviour
Unnecessary commands in integration between `nomad` and `vault`

[/ansible/files/bootstrap/nomad/post/task/vault-integration.yml](https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/ansible/files/bootstrap/nomad/post/task/vault-integration.yml#L1-L6)

```yaml
- name: "{{ service }} - post/vault-integration - create management token for Vault, with global-management policy attached to it"
  shell:
    cmd: consul acl token create -policy-name=global-management -format=json | jq -r .SecretID
  register: secret_id
  environment:
    CONSUL_HTTP_TOKEN: "{{ lookup('env', 'consul_master_token') }}"
```
## Expected behaviour
`/ansible/files/bootstrap/nomad/post/task/vault-integration.yml` contains commands for integration between `nomad` and `vault`

## How to reproduce?
look at playbook

## Suggestion(s)/solution(s) [Optional]
Remove lines 1-6

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone
