### ISSUE TITLE
Pass ~~environment~~ variables to vagrant local_ansible provisioner

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#75]
I mistakenly thought that I can send ENV variable to Vagrant boxes like doing it with Docker.

Approaches that I come up with on how to send arguments to vagrant ansible provisioner:
1. [vagrant-env plugin](https://github.com/gosuri/vagrant-env) - outdated
2. [shell script](https://github.com/hashicorp/vagrant/issues/7015#issuecomment-313850505)
3. ...

I skip the first approach with vagrant-env plugin due to that plugin is outdated. Last updates older than 5 years ago.

## Approach with the shell script
You could check [reference](https://github.com/hashicorp/vagrant/issues/7015#issuecomment-313850505) and Draft PR #78

**Comment by zhenik** [comment]
I would suggest the approach with `ANSIBLE_ARGS` instead of ENV as agrs.

* [Passing command line arguments into Vagrant to configure Ansible Provisioning](https://gist.github.com/phantomwhale/9657134)
* [Running Ansible provisioning by passing arguments in Vagrant
](http://www.inanzzz.com/index.php/post/wfj9/running-ansible-provisioning-by-passing-arguments-in-vagrant)
* [Shared ansible options for vagrant: extra_vars; Official documentation](https://www.vagrantup.com/docs/provisioning/ansible_common.html#extra_vars)

## Default values 
Could be set up in `startup.yml` as
```yml
tasks:
  # Bootstrapping the default policy controls the behavior of a token when there is no matching rule. 
  # Either "allow" or "deny"
  # https://www.consul.io/docs/agent/options.html#acl_default_policy
  - set_fact: consul_agent_acl_default_policy="allow"
    when: consul_agent_acl_default_policy is undefined
  
  # Bootstrapping the acl stanza configures the Nomad agent to enable ACLs and tunes various ACL parameters. 
  # Either true or false
  # https://www.nomadproject.io/docs/configuration/acl 
  - set_fact: nomad_agent_acl_enable=false
    when: nomad_agent_acl_enable is undefined

# some tasks
```
Default values is **good place to write documentation** about variables.
## Option 1: extra_vars in Vagrantfile
`Vagrantfile`
```ruby
Vagrant.configure("2") do |config|
  # some config

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "startup.yml"

    ansible.extra_vars = { 
        consul_agent_acl_default_policy: 'deny',
        nomad_agent_acl_enable: 'true'
        # add more
    }

  end
end
```

## Option 2: extra_vars from Stdin 
`Vagrantfile`
```ruby
Vagrant.configure("2") do |config|
  # some config

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "startup.yml"
    # use to override default mode to test for example
    ansible.raw_arguments = Shellwords.shellsplit(ENV['ANSIBLE_ARGS']) if ENV['ANSIBLE_ARGS']
  end
end
```

Then when user need to provide extra vars or override existing ones
```bash
ANSIBLE_ARGS='--extra-vars "mode=test", "consul_agent_acl_default_policy=deny"' vagrant up --provision
```
